{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "API",
    "description" : "silfricaapi",
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "paths" : { },
  "components" : { }
}